trigger:
- master

pool:
  vmImage: 'ubuntu-16.04'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  publishDir: 'websitepublish'
  # enables debug output
  system.debug: true

steps:
- task: DotNetCoreCLI@2
  name: 'run_build'
  displayName: 'build solution'
  inputs:
    command: 'build'
    arguments: '-c Release'

- task: DotNetCoreCLI@2
  name: 'run_test'
  displayName: 'run tests'
  inputs:
    command: 'test'

- task: DotNetCoreCLI@2
  name: 'publish_website'
  displayName: 'publish website'
  inputs:
    command: 'publish'
    publishWebProjects: true
    arguments: '-c Release -o $(Build.SourcesDirectory)/websitepublish'
    zipAfterPublish: false
    modifyOutputPath: false

- task: CopyFiles@2
  name: 'copy_artifacts'
  displayName: 'copy artifacts to: $(Build.ArtifactStagingDirectory)'
  inputs:
    SourceFolder: '$(Build.SourcesDirectory)/websitepublish'
    Contents: |
     websitepublish/*
    TargetFolder: '$(Build.ArtifactStagingDirectory)'

- task: PublishBuildArtifacts@1
  name: 'publish_artifacts'
  displayName: 'publish artifacts'
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'azure-website'
    publishLocation: 'Container'
