trigger:
- master

pool:
  vmImage: 'ubuntu-16.04'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  publishDir: 'website-publish'
  # enables debug output
  system.debug: true

steps:
- task: DotNetCoreCLI@2
  name: 'build'
  displayName: 'build solution'
  inputs:
    command: 'build'

- task: DotNetCoreCLI@2
  name: 'test'
  displayName: 'run tests'
  inputs:
    command: 'test'

- task: DotNetCoreCLI@2
  name: 'publish'
  displayName: 'publish website'
  inputs:
    command: 'publish'
    publishWebProjects: true
    arguments: '-o website-publish'
    zipAfterPublish: false
    modifyOutputPath: false

- task: CopyFiles@2
  name: 'copy_artifacts'
  displayName: 'copy artifacts to: $(Build.ArtifactStagingDirectory)'
  inputs:
    contents: 'website-publish/**'
    targetFolder: $(Build.ArtifactStagingDirectory)

- task: PublishBuildArtifacts@1
  name: 'publish_artifacts'
  displayName: 'publish artifacts'
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'azure-website'
    publishLocation: 'Container'
