trigger:
- master

pool:
  vmImage: 'ubuntu-16.04'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  # enables debug output
  system.debug: true

stages:
- stage: Build
  jobs:
  - job: Build
    steps:
    - task: UseDotNet@2
      displayName: 'Use .net core sdk 3.1.x'
      name: 'use_sdk'
      inputs:
          version: '3.1.x'
          packageType: 'sdk'
    - task: DotNetCoreCLI@2
      name: 'run_build'
      displayName: 'build solution'
      inputs:
       command: 'build'
       arguments: '-c $(buildConfiguration)'
    - task: DotNetCoreCLI@2
      name: 'run_test'
      displayName: 'run tests'
      inputs:
        command: 'test'
    - task: DotNetCoreCLI@2
      name: 'publish_website'
      displayName: 'publish website'
      inputs:
        command: 'publish'
        publishWebProjects: true
        arguments: '-c $(buildConfiguration) -o $(Build.ArtifactStagingDirectory) -r linux-x64'
        zipAfterPublish: true
        modifyOutputPath: false
    - task: PublishBuildArtifacts@1
      name: 'publish_artifacts'
      displayName: 'publish artifacts'
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'azure-website'
        publishLocation: 'Container'

- stage: Deploy_Test
  dependsOn: Build
  displayName: 'deploy test stage'
  jobs:
  - deployment: 'deployment-schmidt-test'
    variables:
      WebAppName: 'schmidt-test'
    environment: 'test'
    pool: 
      vmImage: 'ubuntu-16.04'
    displayName: 'Deploy test'
    strategy:
     runOnce:
       deploy:
        steps:
          - task: AzureRmWebAppDeployment@4
            displayName: 'schmidt-test app service deploy'
            inputs:
              appType: 'webAppLinux'
              azureSubscription: 'pay-as-you-go'
              ConnectionType: 'AzureRM'
              WebAppName: $(WebAppName)
              packageForLinux: '$(System.WorkFolder)/**/*.zip'

- stage: Deploy_Production
  dependsOn: Deploy_Test
  displayName: 'deploy production stage'
  jobs:
  - deployment: Deploy_Production
    variables:
      WebAppName: 'schmidt'
    pool: 
      vmImage: 'ubuntu-16.04'
    displayName: 'Deploy production'
    strategy:
     runOnce:
       deploy:
        steps:
          - task: AzureRmWebAppDeployment@4
            displayName: 'schmidt app service deploy'
            inputs:
              appType: 'webAppLinux'
              azureSubscription: 'pay-as-you-go'
              ConnectionType: 'AzureRM'
              WebAppName: $(WebAppName)
              packageForLinux: '$(System.WorkFolder)/**/*.zip'
