trigger:
- master

pool:
  vmImage: 'ubuntu-16.04'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  webArtifactName: 'azure-website'
  # enables debug output
  system.debug: true

stages:
- stage: 'stage_build'
  displayName: 'stage build'
  jobs:
  - job: 'build'
    steps:
    - task: UseDotNet@2
      displayName: 'Use .net core sdk 3.1.x'
      name: 'use_sdk'
      inputs:
          version: '3.1.x'
          packageType: 'sdk'
    - task: DotNetCoreCLI@2
      name: 'run_build'
      displayName: 'build solution'
      inputs:
       command: 'build'
       arguments: '-c $(buildConfiguration)'
    - task: DotNetCoreCLI@2
      name: 'publish_website'
      displayName: 'publish website'
      inputs:
        command: 'publish'
        publishWebProjects: true
        arguments: '-c $(buildConfiguration) -o $(Build.ArtifactStagingDirectory) -r linux-x64'
        zipAfterPublish: true
        modifyOutputPath: false
    - task: PublishBuildArtifacts@1
      name: 'publish_artifacts'
      displayName: 'publish artifacts'
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: '$(webArtifactName)'
    - task: PublishPipelineArtifact@1
      name: 'publish_pipeline_artifacts'
      displayName: 'publish pipeline artifacts'
      inputs:
       artifact: '$(webArtifactName)'

- stage: 'stage_test'
  displayName: 'stage test'
  dependsOn:
  - 'stage_build'
  jobs:
    - job: 'test'
      steps:
        - task: DownloadPipelineArtifact@2
          inputs:
            buildType: 'current'
            artifactName: '$(webArtifactName)'
            targetPath: '$(Pipeline.Workspace)'
          
        - task: DotNetCoreCLI@2
          name: 'run_test'
          displayName: 'run tests'
          inputs:
            command: 'test'

- stage: 'stage_deploy_test'
  dependsOn: 
  - 'stage_build'
  - 'stage_test'
  displayName: 'deploy test stage'
  jobs:
  - deployment: 'deployment_schmidt_test'
    environment: 'test'
    variables:
      WebAppName: 'schmidt-test'
    pool: 
      vmImage: 'ubuntu-16.04'
    displayName: 'Deploy test'
    strategy:
     runOnce:
       deploy:
        steps:
          - task: AzureRmWebAppDeployment@4
            displayName: 'schmidt-test app service deploy'
            inputs:
              ConnectionType: 'AzureRM'
              azureSubscription: 'Pay-As-You-Go (4ef5cf54-1584-409a-aff2-01c917c56340)'
              appType: 'webAppLinux'
              WebAppName: '$(WebAppName)'
              packageForLinux: '$(Pipeline.Workspace)/**/*.zip'
              RuntimeStack: 'DOTNETCORE|LTS'

- stage: 'stage_deploy_production'
  dependsOn: 
  - 'stage_build'
  - 'stage_test'
  - 'stage_deploy_test'
  displayName: 'deploy production stage'
  jobs:
  - deployment: 'deploy_schmidt_production'
    environment: 'production'
    variables:
      WebAppName: 'schmidt'
    pool: 
      vmImage: 'ubuntu-16.04'
    displayName: 'Deploy production'
    strategy:
     runOnce:
       deploy:
        steps:
          - download: current
            artifact: '$(webArtifactName)'
          - task: AzureRmWebAppDeployment@4
            displayName: 'schmidt app service deploy'
            inputs:
              ConnectionType: 'AzureRM'
              azureSubscription: 'Pay-As-You-Go (4ef5cf54-1584-409a-aff2-01c917c56340)'
              appType: 'webAppLinux'
              WebAppName: '$(WebAppName)'
              packageForLinux: '$(System.WorkFolder)/**/*.zip'
              RuntimeStack: 'DOTNETCORE|LTS'
