name: 'CI'

trigger:
- master
- feature/*

pool:
  vmImage: 'ubuntu-18.04'
  # vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  webArtifactName: 'azure-website'
  # enables debug output
  # system.debug: true

stages:
- stage: 'Stage_Build'
  displayName: 'Stage - Build'
  jobs:
  - job: 'build'
    steps:
    - task: UseDotNet@2
      displayName: 'Use .net 5.0 sdk'
      name: 'use_sdk'
      inputs:
        version: '5.0.x'
        packageType: 'sdk'

    - task: DotNetCoreCLI@2
      displayName: 'restore packages'
      name: 'restore_packages'
      inputs:
        command: 'restore'

    - task: DotNetCoreCLI@2
      displayName: 'build solution'
      name: 'run_build'
      inputs:
        command: 'build'
        arguments: '-c $(buildConfiguration)'

    - task: DotNetCoreCLI@2
      displayName: 'run tests'
      name: 'run_tests'
      inputs:
        command: test
        arguments: '-c $(buildConfiguration) --collect:"XPlat Code Coverage"'
        projects: '**/*Tests/*.csproj'

    - task: PublishPipelineArtifact@1
      displayName: 'publish code coverage'
      name: 'publish_coverage_file'
      inputs:
        artifact: 'coveragexmlartifact'
        targetPath: '$(Agent.TempDirectory)/'

    - task: PublishCodeCoverageResults@1
      inputs:
        codeCoverageTool: 'Cobertura'
        summaryFileLocation: '$(Agent.TempDirectory)/**/coverage.cobertura.xml'

- stage: 'Stage_Other'
  displayName: 'Stage - Other'
  jobs:
  - job: 'build'
    steps:
    - task: PowerShell@2
      displayName: 'write other'
      name: 'write_other'
      inputs:
        targetType: 'inline'
        script: |
          # Write your PowerShell commands here.
          Write-Host "Other"
