name: 'CI'

trigger:
- master
- feature/*

pool:
  vmImage: 'ubuntu-18.04'
  # vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  webArtifactName: 'azure-website'
  # enables debug output
  system.debug: true

stages:
- stage: 'stage_test_1'
  displayName: 'test'
  jobs:
  - job: 'test'
    steps:
    - task: UseDotNet@2
      displayName: 'Use .net 5.0 sdk'
      name: 'use_sdk'
      inputs:
        version: '5.0.x'
        packageType: 'sdk'

    - task: DotNetCoreCLI@2
      displayName: 'restore packages'
      name: 'restore_packages'
      inputs:
        command: 'restore'

    - task: DotNetCoreCLI@2
      displayName: 'run tests'
      name: 'run_tests'
      inputs:
        command: test
        arguments: '-c $(buildConfiguration) --collect:"XPlat Code Coverage"'
        # arguments: '-c $(buildConfiguration) --verbosity diag --no-build --collect:"XPlat Code Coverage"'
        workingDirectory: $(Pipeline.Workspace)
        projects: '$(Pipeline.Workspace)/AzureWebsite.sln'

    - task: PublishCodeCoverageResults@1
      inputs:
        codeCoverageTool: 'Cobertura'
        summaryFileLocation: '$(Agent.TempDirectory)/**/coverage.cobertura.xml'

    - task: PublishPipelineArtifact@1
      name: 'publish_test_artifacts'
      displayName: 'Publish source code artifact'
      inputs:
        artifact: 'build_artifact'
        targetPath: '$(build.SourcesDirectory)/'


- stage: 'stage_test_2'
  displayName: 'test'
  # dependsOn:
  # - 'stage_build'
  jobs:
  - job: test
    steps:
    - checkout: none
    
    - task: DownloadPipelineArtifact@2
      inputs:
        buildType: 'current'
        artifactName: 'build_artifact'
        targetPath: '$(Pipeline.Workspace)/'

    - task: UseDotNet@2
      displayName: 'Use .net 5.0 sdk'
      name: 'use_sdk'
      inputs:
        version: '5.0.x'
        packageType: 'sdk'

    - task: DotNetCoreCLI@2
      displayName: 'run tests'
      name: 'run_tests'
      inputs:
        command: test
        arguments: '--verbosity diag --no-build --collect:"XPlat Code Coverage"'
        # arguments: '-c $(buildConfiguration) --verbosity diag --no-build --collect:"XPlat Code Coverage"'
        # projects: '$(Pipeline.Workspace)/**/*Tests/*.csproj'
        workingDirectory: $(Pipeline.Workspace)
        projects: '$(Pipeline.Workspace)/AzureWebsite.sln'

    - task: PublishPipelineArtifact@1
      displayName: 'publish code coverage'
      name: 'publish_coverage_file'
      inputs:
        artifact: 'coveragexmlartifact'
        targetPath: '$(Agent.TempDirectory)/'

    - task: PublishCodeCoverageResults@1
      inputs:
        codeCoverageTool: 'Cobertura'
        summaryFileLocation: '$(Agent.TempDirectory)/**/coverage.cobertura.xml'

- stage: 'stage_other'
  displayName: 'other'
  dependsOn:
  - 'stage_test'
  jobs:
  - job: 'other'
    steps:
    - task: PowerShell@2
      displayName: 'write other'
      name: 'write_other'
      inputs:
        targetType: 'inline'
        script: |
          # Write your PowerShell commands here.
          Write-Host "Other"
