name: 'CI'

trigger:
- master

pool:
  # vmImage: 'ubuntu-16.04'
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  webArtifactName: 'azure-website'
  # enables debug output
  system.debug: true

jobs:
- job: 'build'
  steps:
  - task: UseDotNet@2
    displayName: 'Use .net core sdk 3.1.x'
    name: 'use_sdk'
    inputs:
      version: '3.1.x'
      packageType: 'sdk'

  - task: DotNetCoreCLI@2
    displayName: 'restore packages'
    name: 'restore_packages'
    inputs:
      command: 'restore'

  - task: DotNetCoreCLI@2
    displayName: 'build solution'
    name: 'run_build'
    inputs:
      command: 'build'
      arguments: '-c $(buildConfiguration)'

  - task: DotNetCoreCLI@2
    displayName: 'run tests'
    name: 'run_tests'
    inputs:
     command: test
     arguments: '--collect:"XPlat Code Coverage" --results-directory $(Pipeline.Workspace)\TestResults'
     projects: '**/*Tests/*.csproj'

  - task: PublishCodeCoverageResults@1
    inputs:
      codeCoverageTool: 'Cobertura'
      summaryFileLocation: '$(Agent.TempDirectory)\**\coverage.cobertura.xml'